spring.application.name=JwtAuth

#database connection
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#JWT secret key
security.jwt.secret-key=${JWT_SECRET_KEY}
security.jwt.expiration-time=3600000

#mail properties
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${SUPPORT_MAIL}
spring.mail.password=${APP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.config.import=optional:file:.env[.properties]
